# Generated by Django 3.2.12 on 2022-09-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='injured_reserved_list',
        ),
    ]
