# Generated by Django 3.2.12 on 2022-09-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_remove_donations_injured_reserved_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngolist',
            name='zakat_eligible',
        ),
        migrations.AddField(
            model_name='ngolist',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ngolist',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ngolist',
            name='international',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ngolist',
            name='profit',
            field=models.BooleanField(null=True),
        ),
    ]
