# Generated by Django 3.2.12 on 2022-09-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_auto_20220903_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='donation',
        ),
        migrations.AddField(
            model_name='donations',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='ngo.bankaccount'),
        ),
    ]
