# Generated by Django 3.2.12 on 2022-09-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0005_auto_20220903_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngolist',
            name='international',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='profit',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
