# Generated by Django 3.2.12 on 2022-09-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_auto_20220907_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngolist',
            old_name='city',
            new_name='founded',
        ),
    ]
